// Solidity Smart Contract Code Generator
// Maps discovered AMM designs to deploy-ready .sol files

import type { InvariantFamilyId } from "@/lib/discovery-engine";

interface CodegenInput {
  name: string;
  familyId?: InvariantFamilyId | string;
  familyParams?: Record<string, number>;
  bins?: number[];
  score?: number;
  regime?: string;
  author?: string;
}

function sanitizeName(name: string): string {
  return name.replace(/[^a-zA-Z0-9]/g, "").replace(/^[0-9]/, "Pool");
}

function binsToSolidityArray(bins: number[]): string {
  const scaled = bins.map(b => Math.round(b * 1e6));
  const lines: string[] = [];
  for (let i = 0; i < scaled.length; i += 8) {
    lines.push("            " + scaled.slice(i, i + 8).join(", "));
  }
  return lines.join(",\n");
}

function generatePiecewiseBands(input: CodegenInput): string {
  const name = sanitizeName(input.name || "PiecewiseBandsPool");
  const bins = input.bins || [];
  const params = input.familyParams || {};
  return `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title ${name}
 * @notice Piecewise Bands AMM — concentrated liquidity with discrete tick ranges
 * @dev Generated by Invariant Studio | Score: ${input.score?.toFixed(4) ?? "N/A"} | Regime: ${input.regime ?? "unknown"}
 *      Family: piecewise-bands | centerMass=${params.centerMass?.toFixed(3) ?? "?"}, shoulder=${params.shoulder?.toFixed(3) ?? "?"}, skew=${params.skew?.toFixed(3) ?? "?"}
 *      Author: ${input.author ?? "Anonymous"}
 */

import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import "@openzeppelin/contracts/token/ERC20/ERC20.sol";
import "@openzeppelin/contracts/utils/ReentrancyGuard.sol";

contract ${name} is ERC20, ReentrancyGuard {
    IERC20 public immutable tokenA;
    IERC20 public immutable tokenB;

    uint256 public constant NUM_BINS = ${bins.length || 64};
    uint256 public constant PRECISION = 1e18;
    uint256 public constant FEE_BPS = 30; // 0.30%
    uint256 public constant BPS = 10000;

    // Liquidity weights per price bin (scaled by 1e6)
    uint256[${bins.length || 64}] public binWeights;

    uint256 public reserveA;
    uint256 public reserveB;
    uint256 public accumulatedFeesA;
    uint256 public accumulatedFeesB;

    event Swap(address indexed sender, bool aToB, uint256 amountIn, uint256 amountOut, uint256 fee);
    event LiquidityAdded(address indexed provider, uint256 amountA, uint256 amountB, uint256 lpTokens);
    event LiquidityRemoved(address indexed provider, uint256 amountA, uint256 amountB, uint256 lpTokens);
    event FeesCollected(uint256 feesA, uint256 feesB);

    constructor(address _tokenA, address _tokenB) ERC20("${name} LP", "${sanitizeName(input.name || "PBP")}LP") {
        tokenA = IERC20(_tokenA);
        tokenB = IERC20(_tokenB);
        _initBinWeights();
    }

    function _initBinWeights() internal {
        uint256[${bins.length || 64}] memory weights = [
${bins.length > 0 ? binsToSolidityArray(bins) : "            // No bins data — uniform distribution"}
        ];
        for (uint256 i = 0; i < NUM_BINS; i++) {
            binWeights[i] = weights[i];
        }
    }

    /// @notice Get the active bin index based on current price ratio
    function _activeBin() internal view returns (uint256) {
        if (reserveA == 0 || reserveB == 0) return NUM_BINS / 2;
        // log-space mapping: bin = (log(price) - logMin) / binWidth
        // Simplified: use ratio-based linear mapping
        uint256 ratio = (reserveB * PRECISION) / reserveA;
        uint256 bin = (ratio * NUM_BINS) / (10 * PRECISION);
        return bin >= NUM_BINS ? NUM_BINS - 1 : bin;
    }

    /// @notice Effective liquidity at current price using bin weights
    function _effectiveLiquidity() internal view returns (uint256) {
        uint256 bin = _activeBin();
        uint256 totalWeight;
        for (uint256 i = 0; i < NUM_BINS; i++) totalWeight += binWeights[i];
        if (totalWeight == 0) return PRECISION;
        return (binWeights[bin] * PRECISION) / totalWeight;
    }

    /// @notice Swap tokenA for tokenB or vice versa
    function swap(bool aToB, uint256 amountIn) external nonReentrant returns (uint256 amountOut) {
        require(amountIn > 0, "Zero input");

        uint256 fee = (amountIn * FEE_BPS) / BPS;
        uint256 netInput = amountIn - fee;

        uint256 effectiveLiq = _effectiveLiquidity();

        if (aToB) {
            // x * y = k with liquidity weighting
            uint256 newReserveA = reserveA + netInput;
            uint256 k = reserveA * reserveB;
            uint256 adjustedK = k + (effectiveLiq * netInput * reserveB) / (PRECISION * 10);
            amountOut = reserveB - (adjustedK / newReserveA);
            require(amountOut > 0 && amountOut < reserveB, "Insufficient output");

            tokenA.transferFrom(msg.sender, address(this), amountIn);
            tokenB.transfer(msg.sender, amountOut);

            reserveA = newReserveA;
            reserveB -= amountOut;
            accumulatedFeesA += fee;
        } else {
            uint256 newReserveB = reserveB + netInput;
            uint256 k = reserveA * reserveB;
            uint256 adjustedK = k + (effectiveLiq * netInput * reserveA) / (PRECISION * 10);
            amountOut = reserveA - (adjustedK / newReserveB);
            require(amountOut > 0 && amountOut < reserveA, "Insufficient output");

            tokenB.transferFrom(msg.sender, address(this), amountIn);
            tokenA.transfer(msg.sender, amountOut);

            reserveB = newReserveB;
            reserveA -= amountOut;
            accumulatedFeesB += fee;
        }

        emit Swap(msg.sender, aToB, amountIn, amountOut, fee);
    }

    /// @notice Add liquidity proportionally
    function addLiquidity(uint256 amountA, uint256 amountB) external nonReentrant returns (uint256 lpTokens) {
        require(amountA > 0 && amountB > 0, "Zero amounts");

        if (totalSupply() == 0) {
            lpTokens = sqrt(amountA * amountB);
        } else {
            uint256 lpFromA = (amountA * totalSupply()) / reserveA;
            uint256 lpFromB = (amountB * totalSupply()) / reserveB;
            lpTokens = lpFromA < lpFromB ? lpFromA : lpFromB;
        }

        require(lpTokens > 0, "Zero LP tokens");

        tokenA.transferFrom(msg.sender, address(this), amountA);
        tokenB.transferFrom(msg.sender, address(this), amountB);

        reserveA += amountA;
        reserveB += amountB;
        _mint(msg.sender, lpTokens);

        emit LiquidityAdded(msg.sender, amountA, amountB, lpTokens);
    }

    /// @notice Remove liquidity proportionally
    function removeLiquidity(uint256 lpTokens) external nonReentrant returns (uint256 amountA, uint256 amountB) {
        require(lpTokens > 0, "Zero LP tokens");

        amountA = (lpTokens * reserveA) / totalSupply();
        amountB = (lpTokens * reserveB) / totalSupply();

        _burn(msg.sender, lpTokens);

        reserveA -= amountA;
        reserveB -= amountB;

        tokenA.transfer(msg.sender, amountA);
        tokenB.transfer(msg.sender, amountB);

        emit LiquidityRemoved(msg.sender, amountA, amountB, lpTokens);
    }

    /// @notice Collect accumulated fees (callable by anyone — fees go to LP holders)
    function collectFees() external nonReentrant {
        uint256 feesA = accumulatedFeesA;
        uint256 feesB = accumulatedFeesB;
        accumulatedFeesA = 0;
        accumulatedFeesB = 0;
        // Fees remain in reserves, increasing LP token value
        emit FeesCollected(feesA, feesB);
    }

    function sqrt(uint256 x) internal pure returns (uint256 y) {
        if (x == 0) return 0;
        y = x;
        uint256 z = (x + 1) / 2;
        while (z < y) { y = z; z = (x / z + z) / 2; }
    }

    /// @notice View: get all bin weights
    function getBinWeights() external view returns (uint256[${bins.length || 64}] memory) {
        return binWeights;
    }
}
`;
}

function generateAmplifiedHybrid(input: CodegenInput): string {
  const name = sanitizeName(input.name || "AmplifiedHybridPool");
  const bins = input.bins || [];
  const params = input.familyParams || {};
  return `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title ${name}
 * @notice Amplified Hybrid AMM — Curve-style amplified invariant with learned bin weights
 * @dev Generated by Invariant Studio | Score: ${input.score?.toFixed(4) ?? "N/A"} | Regime: ${input.regime ?? "unknown"}
 *      Family: amplified-hybrid | A=${params.amplification?.toFixed(3) ?? "?"}, decay=${params.decay?.toFixed(3) ?? "?"}, bias=${params.bias?.toFixed(3) ?? "?"}
 *      Author: ${input.author ?? "Anonymous"}
 */

import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import "@openzeppelin/contracts/token/ERC20/ERC20.sol";
import "@openzeppelin/contracts/utils/ReentrancyGuard.sol";

contract ${name} is ERC20, ReentrancyGuard {
    IERC20 public immutable tokenA;
    IERC20 public immutable tokenB;

    uint256 public constant NUM_BINS = ${bins.length || 64};
    uint256 public constant PRECISION = 1e18;
    uint256 public constant FEE_BPS = 30;
    uint256 public constant BPS = 10000;

    /// @notice Amplification coefficient (higher = flatter curve near peg)
    uint256 public constant AMP = ${Math.round((params.amplification ?? 5) * 1000)};
    uint256 public constant AMP_PRECISION = 1000;

    uint256[${bins.length || 64}] public binWeights;
    uint256 public reserveA;
    uint256 public reserveB;
    uint256 public accumulatedFeesA;
    uint256 public accumulatedFeesB;

    event Swap(address indexed sender, bool aToB, uint256 amountIn, uint256 amountOut, uint256 fee);
    event LiquidityAdded(address indexed provider, uint256 amountA, uint256 amountB, uint256 lpTokens);
    event LiquidityRemoved(address indexed provider, uint256 amountA, uint256 amountB, uint256 lpTokens);

    constructor(address _tokenA, address _tokenB) ERC20("${name} LP", "${sanitizeName(input.name || "AHP")}LP") {
        tokenA = IERC20(_tokenA);
        tokenB = IERC20(_tokenB);
        _initBinWeights();
    }

    function _initBinWeights() internal {
        uint256[${bins.length || 64}] memory weights = [
${bins.length > 0 ? binsToSolidityArray(bins) : "            // Uniform"}
        ];
        for (uint256 i = 0; i < NUM_BINS; i++) binWeights[i] = weights[i];
    }

    /// @notice StableSwap-inspired getAmountOut with amplified invariant
    function _getAmountOut(bool aToB, uint256 amountIn) internal view returns (uint256) {
        uint256 rA = reserveA;
        uint256 rB = reserveB;
        uint256 D = rA + rB; // sum for the constant-sum component
        uint256 amp = AMP;

        if (aToB) {
            // Hybrid: blend constant-sum (low slippage near peg) with constant-product (safety at extremes)
            uint256 newA = rA + amountIn;
            // Newton iteration for StableSwap invariant
            uint256 newB = _computeY(newA, D, amp);
            return newB < rB ? rB - newB : 0;
        } else {
            uint256 newB = rB + amountIn;
            uint256 newA = _computeY(newB, D, amp);
            return newA < rA ? rA - newA : 0;
        }
    }

    /// @notice Compute counterpart reserve using amplified invariant
    function _computeY(uint256 x, uint256 D, uint256 A) internal pure returns (uint256 y) {
        // Simplified 2-token StableSwap: A*n^n*(x+y) + D = A*D*n^n + D^(n+1)/(n^n*x*y)
        // Newton's method convergence
        y = D / 2;
        uint256 An2 = A * 4 / AMP_PRECISION;
        for (uint256 i = 0; i < 64; i++) {
            uint256 yPrev = y;
            uint256 numerator = y * y + (D * D * D) / (4 * x * y + 1);
            uint256 denominator = 2 * y + An2 * (x + y) - An2 * D + D * D / (4 * x + 1);
            y = denominator > 0 ? numerator / denominator : yPrev;
            if (y > yPrev) { if (y - yPrev <= 1) break; }
            else { if (yPrev - y <= 1) break; }
        }
    }

    function swap(bool aToB, uint256 amountIn) external nonReentrant returns (uint256 amountOut) {
        require(amountIn > 0, "Zero input");
        uint256 fee = (amountIn * FEE_BPS) / BPS;
        uint256 netInput = amountIn - fee;

        amountOut = _getAmountOut(aToB, netInput);
        require(amountOut > 0, "Insufficient output");

        if (aToB) {
            tokenA.transferFrom(msg.sender, address(this), amountIn);
            tokenB.transfer(msg.sender, amountOut);
            reserveA += amountIn;
            reserveB -= amountOut;
            accumulatedFeesA += fee;
        } else {
            tokenB.transferFrom(msg.sender, address(this), amountIn);
            tokenA.transfer(msg.sender, amountOut);
            reserveB += amountIn;
            reserveA -= amountOut;
            accumulatedFeesB += fee;
        }
        emit Swap(msg.sender, aToB, amountIn, amountOut, fee);
    }

    function addLiquidity(uint256 amountA, uint256 amountB) external nonReentrant returns (uint256 lpTokens) {
        if (totalSupply() == 0) { lpTokens = amountA + amountB; }
        else { lpTokens = ((amountA + amountB) * totalSupply()) / (reserveA + reserveB); }
        require(lpTokens > 0, "Zero LP");
        tokenA.transferFrom(msg.sender, address(this), amountA);
        tokenB.transferFrom(msg.sender, address(this), amountB);
        reserveA += amountA; reserveB += amountB;
        _mint(msg.sender, lpTokens);
        emit LiquidityAdded(msg.sender, amountA, amountB, lpTokens);
    }

    function removeLiquidity(uint256 lpTokens) external nonReentrant returns (uint256 amountA, uint256 amountB) {
        amountA = (lpTokens * reserveA) / totalSupply();
        amountB = (lpTokens * reserveB) / totalSupply();
        _burn(msg.sender, lpTokens);
        reserveA -= amountA; reserveB -= amountB;
        tokenA.transfer(msg.sender, amountA); tokenB.transfer(msg.sender, amountB);
        emit LiquidityRemoved(msg.sender, amountA, amountB, lpTokens);
    }

    function getBinWeights() external view returns (uint256[${bins.length || 64}] memory) { return binWeights; }
}
`;
}

function generateTailShielded(input: CodegenInput): string {
  const name = sanitizeName(input.name || "TailShieldedPool");
  const bins = input.bins || [];
  const params = input.familyParams || {};
  return `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title ${name}
 * @notice Tail-Shielded AMM — custom tail protection with moat zones and reinforced extremes
 * @dev Generated by Invariant Studio | Score: ${input.score?.toFixed(4) ?? "N/A"} | Regime: ${input.regime ?? "unknown"}
 *      Family: tail-shielded | tailWeight=${params.tailWeight?.toFixed(3) ?? "?"}, moatWidth=${params.moatWidth?.toFixed(3) ?? "?"}, centerBias=${params.centerBias?.toFixed(3) ?? "?"}
 *      Author: ${input.author ?? "Anonymous"}
 */

import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import "@openzeppelin/contracts/token/ERC20/ERC20.sol";
import "@openzeppelin/contracts/utils/ReentrancyGuard.sol";

contract ${name} is ERC20, ReentrancyGuard {
    IERC20 public immutable tokenA;
    IERC20 public immutable tokenB;

    uint256 public constant NUM_BINS = ${bins.length || 64};
    uint256 public constant PRECISION = 1e18;
    uint256 public constant FEE_BPS = 30;
    uint256 public constant BPS = 10000;
    uint256 public constant TAIL_MULTIPLIER = ${Math.round((params.tailWeight ?? 0.2) * 1000)};
    uint256 public constant TAIL_PRECISION = 1000;

    uint256[${bins.length || 64}] public binWeights;
    uint256 public reserveA;
    uint256 public reserveB;
    uint256 public accumulatedFeesA;
    uint256 public accumulatedFeesB;

    event Swap(address indexed sender, bool aToB, uint256 amountIn, uint256 amountOut, uint256 fee);
    event LiquidityAdded(address indexed provider, uint256 amountA, uint256 amountB, uint256 lpTokens);
    event LiquidityRemoved(address indexed provider, uint256 amountA, uint256 amountB, uint256 lpTokens);

    constructor(address _tokenA, address _tokenB) ERC20("${name} LP", "${sanitizeName(input.name || "TSP")}LP") {
        tokenA = IERC20(_tokenA);
        tokenB = IERC20(_tokenB);
        _initBinWeights();
    }

    function _initBinWeights() internal {
        uint256[${bins.length || 64}] memory weights = [
${bins.length > 0 ? binsToSolidityArray(bins) : "            // Uniform"}
        ];
        for (uint256 i = 0; i < NUM_BINS; i++) binWeights[i] = weights[i];
    }

    /// @notice Tail protection: dynamic fee scaling at extreme price ratios
    function _dynamicFee(uint256 amountIn) internal view returns (uint256) {
        uint256 baseFee = (amountIn * FEE_BPS) / BPS;
        if (reserveA == 0 || reserveB == 0) return baseFee;

        // Increase fee when reserves are heavily imbalanced (tail protection)
        uint256 ratio = reserveA > reserveB
            ? (reserveA * PRECISION) / reserveB
            : (reserveB * PRECISION) / reserveA;

        if (ratio > 5 * PRECISION) {
            // In tail zone: fee scales up by tail multiplier
            return baseFee + (baseFee * TAIL_MULTIPLIER) / TAIL_PRECISION;
        }
        return baseFee;
    }

    function swap(bool aToB, uint256 amountIn) external nonReentrant returns (uint256 amountOut) {
        require(amountIn > 0, "Zero input");

        uint256 fee = _dynamicFee(amountIn);
        uint256 netInput = amountIn - fee;

        if (aToB) {
            uint256 newA = reserveA + netInput;
            amountOut = reserveB - (reserveA * reserveB) / newA;
            require(amountOut > 0 && amountOut < reserveB, "Bad output");
            tokenA.transferFrom(msg.sender, address(this), amountIn);
            tokenB.transfer(msg.sender, amountOut);
            reserveA = newA; reserveB -= amountOut;
            accumulatedFeesA += fee;
        } else {
            uint256 newB = reserveB + netInput;
            amountOut = reserveA - (reserveA * reserveB) / newB;
            require(amountOut > 0 && amountOut < reserveA, "Bad output");
            tokenB.transferFrom(msg.sender, address(this), amountIn);
            tokenA.transfer(msg.sender, amountOut);
            reserveB = newB; reserveA -= amountOut;
            accumulatedFeesB += fee;
        }
        emit Swap(msg.sender, aToB, amountIn, amountOut, fee);
    }

    function addLiquidity(uint256 amountA, uint256 amountB) external nonReentrant returns (uint256 lpTokens) {
        if (totalSupply() == 0) { lpTokens = sqrt(amountA * amountB); }
        else {
            uint256 lpA = (amountA * totalSupply()) / reserveA;
            uint256 lpB = (amountB * totalSupply()) / reserveB;
            lpTokens = lpA < lpB ? lpA : lpB;
        }
        require(lpTokens > 0, "Zero LP");
        tokenA.transferFrom(msg.sender, address(this), amountA);
        tokenB.transferFrom(msg.sender, address(this), amountB);
        reserveA += amountA; reserveB += amountB;
        _mint(msg.sender, lpTokens);
        emit LiquidityAdded(msg.sender, amountA, amountB, lpTokens);
    }

    function removeLiquidity(uint256 lpTokens) external nonReentrant returns (uint256 amountA, uint256 amountB) {
        amountA = (lpTokens * reserveA) / totalSupply();
        amountB = (lpTokens * reserveB) / totalSupply();
        _burn(msg.sender, lpTokens);
        reserveA -= amountA; reserveB -= amountB;
        tokenA.transfer(msg.sender, amountA); tokenB.transfer(msg.sender, amountB);
        emit LiquidityRemoved(msg.sender, amountA, amountB, lpTokens);
    }

    function sqrt(uint256 x) internal pure returns (uint256 y) {
        if (x == 0) return 0;
        y = x; uint256 z = (x + 1) / 2;
        while (z < y) { y = z; z = (x / z + z) / 2; }
    }

    function getBinWeights() external view returns (uint256[${bins.length || 64}] memory) { return binWeights; }
}
`;
}

/** Generate Solidity contract source code for an AMM design */
export function generateSolidity(input: CodegenInput): { code: string; filename: string; contractName: string } {
  const familyId = input.familyId || "piecewise-bands";
  const contractName = sanitizeName(input.name || "InvariantPool");

  let code: string;
  switch (familyId) {
    case "amplified-hybrid":
      code = generateAmplifiedHybrid(input);
      break;
    case "tail-shielded":
      code = generateTailShielded(input);
      break;
    default:
      code = generatePiecewiseBands(input);
      break;
  }

  return {
    code,
    filename: `${contractName}.sol`,
    contractName,
  };
}

/** Download a .sol file */
export function downloadSolidity(input: CodegenInput): void {
  const { code, filename } = generateSolidity(input);
  const blob = new Blob([code], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
